version: '3'

services:
  app:
    image: ${IMAGE_URI}:${IMAGE_TAG}
    build:
      context: ./.
      dockerfile: Dockerfile
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: "node app.js"
