version: 2.1
orbs:
  docker: circleci/docker@1.5.0
  node: circleci/node@4.2.1

commands:
  git_checkout_from_cache:
    description: "Git checkout"
    steps:
      - checkout

  build:
    description: "npm install and save cache"
    steps:
      - run:
          name: Update NPM
          command: npm install --production
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Update node modules
          command: npm install --production
      - run:
          name: JUnit test formatter
          command: npm install mocha-junit-reporter
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
          - ./node_modules
  test:
    description: "Run test"
    steps:
      - run:
          name: Run tests
          command: npm test

jobs:

  build_and_test:
    docker:
      - image: circleci/node:12.18.0-stretch
        environment:
          ACCEPT_EULA: "Y"
    steps:
      - git_checkout_from_cache
      - build
      - test


workflows:
  tests:
    jobs:
      - node/test:
          filters:
            branches:
              ignore: /^master$/

  build_and_test:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
              - master
